version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: otp_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: otp_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_otp_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: otp_redis
    restart: always
    ports:
      - "6379:6379"

  go-app:
    build: .
    container_name: otp_service
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASS=pass
      - DB_NAME=otp_service
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EMAIL_API_KEY=your_sendgrid_key
      - SMS_API_KEY=your_textbelt_key
      - JWT_SECRET=your_secret_key
    ports:
      - "8080:8080"
    volumes:
      - .:/app  # Mounts local project into the container
    working_dir: /app  # Sets working directory inside the container
    command: go run ./cmd/main.go  # Runs Go application

volumes:
  postgres_otp_data:
